# Model Training Script
### This script is used to create MLP (Multi Layer Perceptron) Classifier for classifying mango variety using feature vector of mango leaf.

In [25]:
import os
import numpy as np
import pandas
import joblib
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

### Prepare dataset directory and load dataset csv file into Pandas DataFrame

In [26]:
# Leaves Dataset Folder Name
dataset_folder = 'MangoLeavesDatabase'
# Leaves Dataset File Name
dataset_filename = 'labeled_dataset.csv'
# Current working directory
cwd = os.getcwd()
# Load the dataset from CSV file into pandas DataFrame
data = pandas.read_csv(os.path.join(cwd, dataset_folder, dataset_filename))

### Create lists of feature vectors and corresponding labels from dataframe

In [27]:
# Mapping of string labels to numeric value
label_map = {
    'alphonso': 0,
    'amrapali': 1,
    'chausa': 2,
    'dusheri': 3,
    'langra': 4
}
# List of feature vectors
X = data.iloc[:, :len(data.columns)-1].to_numpy(copy=True)
# List of corresponding label to each feature vector
Y = data.iloc[:,-1].to_numpy(copy=True)
# Map string labels to numeric values
Y = np.array([label_map[label] for label in Y])

### Create and Split Training and Test Data

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.75, test_size=0.25, shuffle=True)

### Train and Test MLP Classifier

In [29]:
# Train MLP Classifer Model using training data
classifier = MLPClassifier(hidden_layer_sizes=(10,10,10), max_iter=2000)

classifier.fit(X_train, Y_train)

# Model predictions using test data
predictions = classifier.predict(X_test) 
  
# model accuracy for X_test
accuracy = classifier.score(X_test, Y_test)
  
# creating a confusion matrix
cm = confusion_matrix(Y_test, predictions)

In [30]:
print(accuracy)

0.54


In [31]:
print(cm)

[[47  7 10  2  6]
 [11 27  0 36 14]
 [ 7  1 64  0  7]
 [ 6 25  0 51  1]
 [19  4 22  6 27]]


### Serialize MLP classifier to a file

In [32]:
model_file_name = "mango_leaf_classifier.mlp"
# Writes MLP classifier to a file
joblib.dump(classifier, model_file_name)

['mango_leaf_classifier.mlp']