# Model Training Script
### This script is used to create SVM Classifier model for classifying mango variety using feature vector of mango leaf.

In [353]:
import os
import numpy as np
import pandas
import joblib
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

### Prepare dataset directory and load dataset csv file into Pandas DataFrame

In [354]:
# Leaves Dataset Folder Name
dataset_folder = 'MangoLeavesDatabase'
# Leaves Dataset File Name
dataset_filename = 'labeled_haar_dataset.csv'
# Current working directory
cwd = os.getcwd()
# Load the dataset from CSV file into pandas DataFrame
data = pandas.read_csv(os.path.join(cwd, dataset_folder, dataset_filename))

### Create lists of feature vectors and corresponding labels from dataframe

In [355]:
# Mapping of string labels to numeric value
label_map = {
    'alphonso': 0,
    'amrapali': 1,
    'chausa': 2,
    'dusheri': 3,
    'langra': 4
}
# List of feature vectors
X = data.iloc[:, 1:len(data.columns)-1].to_numpy(copy=True)
# List of corresponding label to each feature vector
Y = data.iloc[:,-1].to_numpy(copy=True)
# Map string labels to numeric values
Y = np.array([label_map[label] for label in Y])

### Create and Split Training and Test Data

In [356]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.75, test_size=0.25, shuffle=True)

### Train and Test Support Vector Classifier

In [357]:
# Train SVM Model using training data
svm_model = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo').fit(X_train, Y_train)

# Model predictions using test data
svm_predictions = svm_model.predict(X_test) 
  
# model accuracy for X_test   
accuracy = svm_model.score(X_test, Y_test)
  
# creating a confusion matrix
cm = confusion_matrix(Y_test, svm_predictions)

In [350]:
print(accuracy)

0.35398230088495575


In [351]:
print(cm)

[[11  8  6  7 17]
 [ 6 18  1  2  6]
 [ 5  0  3  7 26]
 [19  2  6  6 16]
 [ 1  0  4  7 42]]


### Serialize SVM model to a file

In [352]:
model_file_name = "mango_leaf_classifier.svm"
# Writes SVM model to a file
joblib.dump(svm_model, model_file_name)

['mango_leaf_classifier.svm']